export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER_FIRST_NAME = "UPDATE_USER_FIRST_NAME";
export const UPDATE_USER_LAST_NAME = "UPDATE_USER_LAST_NAME";
export const UPDATE_USER_AGE = "UPDATE_USER_AGE";
export const UPDATE_USER_PROFILE_PICTURE = "UPDATE_USER_PROFILE_PICTURE";
